export interface ArtistData {
  name: string
  email: string
  vatNumber: string
  isEuNonGerman: boolean
  notes: string
}

export const artistsData: ArtistData[] = [
  { name: "Aevum", email: "", vatNumber: "", isEuNonGerman: true, notes: "Italy | Symphonic Gothic Metal" },
  { name: "Agnis", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Industrial Metal" },
  { name: "Amore Ad Lunam", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Pop / Electronic" },
  { name: "Antibody", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Harsh Electro / TBM" },
  { name: "Ashes'N'Android", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Synthpop / TBM" },
  { name: "Apnoie", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Dark Electro" },
  { name: "Auger", email: "", vatNumber: "", isEuNonGerman: false, notes: "UK | Darkwave / Melodic Rock" },
  { name: "Balduvian Bears", email: "", vatNumber: "", isEuNonGerman: false, notes: "USA | Electro / Industrial" },
  { name: "Basscalate", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Techno / EBM" },
  { name: "Basszilla", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Industrial Bass / Dubstep" },
  { name: "Binary Division", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Synthpop / EBM" },
  { name: "Blackbook", email: "", vatNumber: "", isEuNonGerman: true, notes: "Switzerland / Netherlands | Indie Pop / New Wave" },
  { name: "Breed Machine", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Nu Metal / Hardcore" },
  { name: "C Z A R I N A", email: "", vatNumber: "", isEuNonGerman: false, notes: "USA | Progressive Darkwave" },
  { name: "Cattac", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Rock / Goth" },
  { name: "Cernunnos", email: "", vatNumber: "", isEuNonGerman: false, notes: "Argentina | Folk" },
  { name: "Chabtan", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Death Metal / Mayan Metal" },
  { name: "Circuit Preacher", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Industrial Rock" },
  { name: "Dance My Darling", email: "", vatNumber: "", isEuNonGerman: false, notes: "Russia | Gothic Pop / Synthwave" },
  { name: "Darkcell", email: "", vatNumber: "", isEuNonGerman: false, notes: "Australia | Industrial Rock" },
  { name: "Dead Lights", email: "", vatNumber: "", isEuNonGerman: false, notes: "UK / Netherlands | Industrial Pop" },
  { name: "Dust In Mind", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Modern Metal" },
  { name: "Extize", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Cyberpunk / Industrial" },
  { name: "Fallcie", email: "", vatNumber: "", isEuNonGerman: false, notes: "Russia | Female Fronted Metal" },
  { name: "Fourth Circle", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Symphonic Metal" },
  { name: "Freak Injection", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Electro Rock / Glitch" },
  { name: "Freaky Mind", email: "", vatNumber: "", isEuNonGerman: false, notes: "Russia | Aggrotech / Electro" },
  { name: "Frozen Plasma", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Futurepop / Synthpop" },
  { name: "H.EXE", email: "", vatNumber: "", isEuNonGerman: true, notes: "Poland | Dark Electro / Industrial Metal" },
  { name: "Her Own World", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Darkwave / Industrial" },
  { name: "Kami No Ikari", email: "", vatNumber: "", isEuNonGerman: true, notes: "France | Death Metal" },
  { name: "Kyunaa", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Pop" },
  { name: "Lamori", email: "", vatNumber: "", isEuNonGerman: false, notes: "Sweden | Gothic Metal" },
  { name: "Logical Terror", email: "", vatNumber: "", isEuNonGerman: true, notes: "Italy | Modern Metal" },
  { name: "Minimum Viable Produkt", email: "", vatNumber: "", isEuNonGerman: false, notes: "USA | EBM" },
  { name: "Misscore", email: "", vatNumber: "", isEuNonGerman: true, notes: "Poland | Modern Metal" },
  { name: "Morgenstern", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Neue Deutsche Härte" },
  { name: "Mortes", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Wave / Gothic" },
  { name: "Moyra", email: "", vatNumber: "", isEuNonGerman: true, notes: "Poland | Melodic Death Metal" },
  { name: "Neuroklast", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Industrial / Aggrotech" },
  { name: "Ocean Dark", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Metal" },
  { name: "Octo Crura", email: "", vatNumber: "", isEuNonGerman: true, notes: "Italy | Dark Ritual / Gothic" },
  { name: "Omnimar", email: "", vatNumber: "", isEuNonGerman: false, notes: "Russia | Dark Pop" },
  { name: "Pzytechz", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Electro" },
  { name: "Reaper", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Electro" },
  { name: "Sickret", email: "", vatNumber: "", isEuNonGerman: false, notes: "Switzerland | Nu Metal" },
  { name: "Smash Hit Combo", email: "", vatNumber: "", isEuNonGerman: false, notes: "France | Nu Metal" },
  { name: "Stoneman", email: "", vatNumber: "", isEuNonGerman: false, notes: "Switzerland | NDH" },
  { name: "SynthAttack", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Electro / EBM" },
  { name: "T3rr0r 3rr0r", email: "", vatNumber: "", isEuNonGerman: false, notes: "Spain | Dark Electro / EBM" },
  { name: "The Black Capes", email: "", vatNumber: "", isEuNonGerman: true, notes: "Greece | Gothic Rock" },
  { name: "The Original Sin", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Metal" },
  { name: "The Silverblack", email: "", vatNumber: "", isEuNonGerman: true, notes: "Italy | Industrial Metal" },
  { name: "Toal", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Ambient / New Wave" },
  { name: "Vioflesh", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Dark Pop / Synthpop" },
  { name: "White Ritual", email: "", vatNumber: "", isEuNonGerman: false, notes: "Germany | Modern Metal" },
  { name: "Yuzna", email: "", vatNumber: "", isEuNonGerman: false, notes: "Italy | punk rock" }
]
