import type { Artist, Release, NewsPost, Video } from '@/types'

export const mockArtists: Artist[] = [
  {
    id: '1',
    name: 'C Z A R I N A',
    slug: 'czarina',
    bio: 'Dark electronic pop artist pushing boundaries with haunting vocals and industrial beats. CZARINA crafts atmospheric soundscapes that blend synthetic textures with raw emotion, creating music that pulses with intensity.',
    genres: ['Darkpop', 'Electronic', 'Industrial'],
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/czarina',
    instagramUrl: 'https://instagram.com/czarina',
    youtubeUrl: 'https://youtube.com/@czarina',
    websiteUrl: 'https://czarina.music',
    featured: true,
    isVisible: true,
  },
  {
    id: '2',
    name: 'BLACKBOOK',
    slug: 'blackbook',
    bio: 'Merging gothic rock with modern metal sensibilities, BLACKBOOK delivers powerful performances that resonate with darkness and intensity. Their sound is a perfect marriage of melody and aggression.',
    genres: ['Gothic Rock', 'Metal', 'Dark Rock'],
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/blackbook',
    instagramUrl: 'https://instagram.com/blackbook',
    youtubeUrl: 'https://youtube.com/@blackbook',
    featured: true,
    isVisible: true,
  },
  {
    id: '3',
    name: 'SMASH HIT COMBO',
    slug: 'smash-hit-combo',
    bio: 'High-energy alternative rock with punk influences. Raw, unfiltered, and unapologetically loud. SMASH HIT COMBO brings explosive energy to every performance, channeling pure rebellion.',
    genres: ['Alternative', 'Punk', 'Rock'],
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/smashhitcombo',
    instagramUrl: 'https://instagram.com/smashhitcombo',
    featured: false,
    isVisible: true,
  },
  {
    id: '4',
    name: 'FROZEN PLASMA',
    slug: 'frozen-plasma',
    bio: 'Pioneers of the synthpop revival, FROZEN PLASMA combines retro electronic aesthetics with contemporary production. Their icy melodies and pulsating rhythms define the modern synthwave movement.',
    genres: ['Synthpop', 'Electro', 'Synth wave'],
    imageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/frozenplasma',
    youtubeUrl: 'https://youtube.com/@frozenplasma',
    websiteUrl: 'https://frozenplasma.net',
    featured: false,
    isVisible: true,
  },
  {
    id: '5',
    name: 'CATTAC',
    slug: 'cattac',
    bio: 'Aggressive industrial metal with mechanical precision. CATTAC delivers sonic warfare through complex rhythms and distorted vocals, creating a relentless assault of sound that\'s both brutal and hypnotic.',
    genres: ['Industrial', 'Metal', 'EBM'],
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/cattac',
    youtubeUrl: 'https://youtube.com/@cattac',
    featured: false,
    isVisible: true,
  },
  {
    id: '6',
    name: 'NEON VOID',
    slug: 'neon-void',
    bio: 'Cyberpunk-inspired electronic artist creating dystopian soundscapes. The future sounds dark with NEON VOID. Their music paints vivid pictures of neon-lit streets and digital decay.',
    genres: ['Electronic', 'Industrial', 'Darkwave'],
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=800&fit=crop&q=80',
    spotifyUrl: 'https://open.spotify.com/artist/neonvoid',
    instagramUrl: 'https://instagram.com/neonvoid',
    youtubeUrl: 'https://youtube.com/@neonvoid',
    featured: false,
    isVisible: true,
  }
]

export const mockReleases: Release[] = [
  {
    id: '1',
    title: 'Polymorph',
    artistId: '1',
    artistName: 'C Z A R I N A',
    releaseDate: '2024-03-15',
    coverArt: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=800&h=800&fit=crop&q=80',
    type: 'album',
    spotifyUrl: 'https://open.spotify.com/album/polymorph',
    youtubeUrl: 'https://youtube.com/playlist?list=polymorph',
    featured: true,
    isVisible: true,
    isPromo: false,
  },
  {
    id: '2',
    title: 'Monsters',
    artistId: '2',
    artistName: 'BLACKBOOK',
    releaseDate: '2024-04-24',
    coverArt: 'https://images.unsplash.com/photo-1518893883800-45cd0954574b?w=800&h=800&fit=crop&q=80',
    type: 'single',
    spotifyUrl: 'https://open.spotify.com/track/monsters',
    youtubeUrl: 'https://youtube.com/watch?v=monsters',
    featured: true,
    isVisible: true,
    isPromo: false,
  },
  {
    id: '3',
    title: 'Split',
    artistId: '3',
    artistName: 'SMASH HIT COMBO',
    releaseDate: '2024-04-17',
    coverArt: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=800&fit=crop&q=80',
    type: 'single',
    spotifyUrl: 'https://open.spotify.com/track/split',
    youtubeUrl: 'https://youtube.com/watch?v=split',
    featured: true,
    isVisible: true,
    isPromo: false,
  },
  {
    id: '4',
    title: 'Synthetic Dreams',
    artistId: '4',
    artistName: 'FROZEN PLASMA',
    releaseDate: '2024-03-27',
    coverArt: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&h=800&fit=crop&q=80',
    type: 'ep',
    spotifyUrl: 'https://open.spotify.com/album/synthetic-dreams',
    featured: false,
    isVisible: true,
    isPromo: false,
  },
  {
    id: '5',
    title: 'Machine Heart',
    artistId: '5',
    artistName: 'CATTAC',
    releaseDate: '2024-02-14',
    coverArt: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=800&fit=crop&q=80',
    type: 'album',
    spotifyUrl: 'https://open.spotify.com/album/machine-heart',
    youtubeUrl: 'https://youtube.com/playlist?list=machineheart',
    featured: false,
    isVisible: true,
    isPromo: false,
  },
  {
    id: '6',
    title: 'Digital Decay',
    artistId: '6',
    artistName: 'NEON VOID',
    releaseDate: '2024-05-08',
    coverArt: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=800&fit=crop&q=80',
    type: 'single',
    spotifyUrl: 'https://open.spotify.com/track/digital-decay',
    featured: false,
    isVisible: true,
    isPromo: false,
  }
]

export const mockNews: NewsPost[] = [
  {
    id: '1',
    title: 'BLACKBOOK Returns with Brand New Single "Monsters"',
    excerpt: 'With "MONSTERS," BLACKBOOK deliver one of their most emotionally direct and introspective releases to date. Blending atmospheric modern rock with raw, honest lyricism.',
    content: 'Full article content would go here...',
    publishedAt: '2024-04-24',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&h=600&fit=crop',
    slug: 'blackbook-monsters',
    featured: false,
    isPressOnly: false,
    status: 'published',
  },
  {
    id: '2',
    title: 'THROATCUT Signs with darkTunes Music Group',
    excerpt: 'We are thrilled to announce the signing of brutal metalcore act THROATCUT to the darkTunes roster. Prepare for uncompromising heaviness.',
    content: 'Full article content would go here...',
    publishedAt: '2024-05-01',
    imageUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=1200&h=600&fit=crop',
    slug: 'throatcut-signing',
    featured: false,
    isPressOnly: false,
    status: 'published',
  },
  {
    id: '3',
    title: 'C Z A R I N A Unveils "Polymorph" - A Genre-Defying Masterpiece',
    excerpt: 'The highly anticipated album "Polymorph" showcases CZARINA\'s evolution as a darkpop visionary, pushing sonic boundaries further than ever.',
    content: 'Full article content would go here...',
    publishedAt: '2024-03-15',
    slug: 'czarina-polymorph',
    featured: false,
    isPressOnly: false,
    status: 'published',
  },
  {
    id: '4',
    title: 'darkTunes Announces 2024 European Tour Dates',
    excerpt: 'Get ready for the darkTunes showcase tour hitting major European cities this fall. Featuring CATTAC, NEON VOID, and surprise guests.',
    content: 'Full article content would go here...',
    publishedAt: '2024-05-03',
    slug: 'european-tour-2024',
    featured: false,
    isPressOnly: false,
    status: 'published',
  }
]

export const mockVideos: Video[] = [
  {
    id: '1',
    title: 'Monsters (Official Music Video)',
    artistName: 'BLACKBOOK',
    youtubeId: 'Bx51eegLTY8',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518893883800-45cd0954574b?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-04-24',
    isVisible: true,
    isShort: false,
  },
  {
    id: '2',
    title: 'Polymorph (Visualizer)',
    artistName: 'C Z A R I N A',
    youtubeId: '9RBzsjga73s',
    thumbnailUrl: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-03-15',
    isVisible: true,
    isShort: false,
  },
  {
    id: '3',
    title: 'Split (Official Video)',
    artistName: 'SMASH HIT COMBO',
    youtubeId: 'kXYiU_JCYtU',
    thumbnailUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-04-17',
    isVisible: true,
    isShort: false,
  },
  {
    id: '4',
    title: 'Synthetic Dreams (Live Session)',
    artistName: 'FROZEN PLASMA',
    youtubeId: 'OPf0YbXqDm0',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-03-27',
    isVisible: true,
    isShort: false,
  },
  {
    id: '5',
    title: 'Machine Heart (Official Music Video)',
    artistName: 'CATTAC',
    youtubeId: 'WaMB0rR7sTU',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-02-14',
    isVisible: true,
    isShort: false,
  },
  {
    id: '6',
    title: 'Digital Decay (Visualizer)',
    artistName: 'NEON VOID',
    youtubeId: 'bjPqsDU0j2I',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&h=675&fit=crop&q=80',
    publishedAt: '2024-05-08',
    isVisible: true,
    isShort: false,
  }
]
