import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

export default tseslint.config(
  // next-env.d.ts is auto-generated by Next.js and contains triple-slash references
  // that violate @typescript-eslint/triple-slash-reference — exclude it from linting.
  { ignores: ['dist', 'node_modules', 'next-env.d.ts', '.next'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  // Next.js App Router files legitimately export non-component values alongside the
  // default component export: `metadata`, `dynamic`, `generateStaticParams`, etc.
  // Disable react-refresh/only-export-components for the entire app/ directory.
  {
    files: ['app/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  // Shadcn UI components follow the pattern of co-exporting helper hooks/variant
  // functions alongside the component (e.g. `useSidebar`, `buttonVariants`).
  // Context files similarly co-export their consumer hooks.
  // These are intentional library patterns — disable the rule for these paths.
  {
    files: ['src/components/ui/**/*.{ts,tsx}', 'src/contexts/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
)

