import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import nextPlugin from '@next/eslint-plugin-next'

export default tseslint.config(
  // next-env.d.ts is auto-generated by Next.js and contains triple-slash references
  // that violate @typescript-eslint/triple-slash-reference — exclude it from linting.
  { ignores: ['dist', 'node_modules', 'next-env.d.ts', '.next'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  // Use the flat-config export so Next.js detects the plugin during `next build`.
  nextPlugin.flatConfig.recommended,
)

